#!/usr/bin/env python3
"""Semi-automated reference verification against Crossref (with DOI lookup).

Reads a Markdown file containing citation lines (e.g. the appendix generated by
extract_references.py) and, for each line, resolves the DOI or queries Crossref
by author + year + title words. It outputs a candidate check table
(references.check.md) with a suggested mark, so the organizer only needs to
review the evidence instead of searching every reference by hand.

Usage:
  python verify_references.py <references.md> [-o references.check.md]
"""

import argparse
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) DeepSeekSkill/1.0 (mailto:example@example.com)"
DOI_RE = re.compile(r"10\.\d{4,9}/[^\s,;)\]（）】，。]+")
YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
SURNAME_RE = re.compile(r"(?<![\w-])([A-Z][A-Za-z\u00C0-\u024F\-]{2,})\s+(?:et al\.?|&|,|\(19|\(20|\.|$)")
STOP = {"the", "and", "of", "in", "on", "for", "with", "from", "to", "a", "an", "via", "by", "at", "its", "their", "his", "her"}


def fetch_json(url, timeout=25):
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def tokens(text):
    return {w for w in re.findall(r"[A-Za-z][A-Za-z0-9'\-]{2,}", text.lower()) if w not in STOP}


def jaccard(a, b):
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def parse_citation(line):
    line = re.sub(r"^[-*+]\s*", "", line).strip()
    line = re.sub(r"^[✅⚠️❌]\s*", "", line)
    line = re.sub(r"（来源对话：.*$", "", line).strip()
    query = re.split(r"\s*—\s*|；实为|，实为", line)[0].strip()
    line = re.sub(r"^https?://doi\.org/", "", line).strip()
    doi = None
    m = DOI_RE.search(line)
    if m:
        doi = m.group(0).rstrip(".")
    year = None
    m = YEAR_RE.search(line)
    if m:
        year = int(m.group(0))
    surname = None
    m = SURNAME_RE.search(line)
    if m:
        surname = m.group(1)
    return {"line": line, "query": query, "doi": doi, "year": year, "surname": surname}


def title_of(item):
    t = item.get("title") or []
    return t[0] if t else ""


def authors_of(item):
    out = []
    for a in item.get("author", []):
        fam = a.get("family")
        if fam:
            out.append(fam)
    return out


def year_of(item):
    issued = item.get("issued") or {}
    parts = issued.get("date-parts") or [[None]]
    return parts[0][0]


def score_candidate(ref, item):
    score = 0.0
    cand_authors = authors_of(item)
    cand_year = year_of(item)
    cand_title = title_of(item)
    if ref["surname"] and any(a.lower() == ref["surname"].lower() for a in cand_authors):
        score += 0.4
    if ref["year"] and cand_year and abs(int(cand_year) - ref["year"]) <= 1:
        score += 0.3
    qt = tokens(re.sub(r"\(.*?\)", " ", ref["line"]))
    score += 0.3 * jaccard(qt, tokens(cand_title))
    return round(min(score, 1.0), 2), cand_title, cand_authors, cand_year


def suggest_mark(score, found):
    if not found:
        return "❌(倾向)"
    if score >= 0.75:
        return "✅(倾向)"
    if score >= 0.45:
        return "⚠️(倾向)"
    return "❌(倾向)"


def verify_one(ref):
    if ref["doi"]:
        try:
            data = fetch_json(f"https://api.crossref.org/works/{urllib.parse.quote(ref['doi'])}")
            item = data["message"]
            if not (ref["surname"] or ref["year"]):
                return {
                    "ref": ref["line"],
                    "mark": "⚠️(需比对)",
                    "score": "-",
                    "matched": f"{title_of(item)} | {', '.join(authors_of(item)[:3])} | {year_of(item)}",
                    "via": f"DOI {ref['doi']}（可解析，匹配与否需人工比对）",
                }
            score, title, authors, year = score_candidate(ref, item)
            return {
                "ref": ref["line"],
                "mark": suggest_mark(score, True),
                "score": score,
                "matched": f"{title} | {', '.join(authors[:3])} | {year}",
                "via": f"DOI {ref['doi']}",
            }
        except Exception as exc:  # noqa: BLE001
            # DOI 未命中时回退到书目检索，看论文是否以其他 DOI 存在
            fallback = _bibliographic(ref)
            fallback["ref"] = ref["line"]
            fallback["via"] = f"DOI {ref['doi']} 未命中（{exc}），回退标题检索"
            return fallback

    return _bibliographic(ref, ref["query"])


def _bibliographic(ref, query=None):
    query = query or ref["query"] or ref["line"][:160].replace("\n", " ")
    try:
        url = "https://api.crossref.org/works?rows=4&query.bibliographic=" + urllib.parse.quote(query)
        data = fetch_json(url)
        items = data.get("message", {}).get("items", [])
    except Exception as exc:  # noqa: BLE001
        return {"ref": ref["line"], "mark": "⚠️(网络失败)", "score": 0, "matched": str(exc), "via": "Crossref"}
    if not items:
        return {"ref": ref["line"], "mark": "❌(倾向)", "score": 0, "matched": "Crossref 无结果", "via": "Crossref"}
    best = None
    for item in items:
        s, t, a, y = score_candidate(ref, item)
        if best is None or s > best[0]:
            best = (s, t, a, y)
    s, t, a, y = best
    return {
        "ref": ref["line"],
        "mark": suggest_mark(s, True),
        "score": s,
        "matched": f"{t} | {', '.join(a[:3])} | {y}",
        "via": "Crossref 书目检索",
    }


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:  # noqa: BLE001
        pass
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("input", help="包含参考文献行的 Markdown 文件（如 extract_references.py 生成的 references.md）")
    parser.add_argument("-o", "--output", default="references.check.md", help="输出核查候选表（默认 references.check.md）")
    parser.add_argument("--limit", type=int, default=0, help="可选：最多核查前 N 条（0=全部）")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        sys.exit(f"输入文件不存在: {input_path}")
    lines = input_path.read_text(encoding="utf-8-sig").splitlines()
    refs = []
    for ln in lines:
        s = ln.strip()
        if not s.startswith(("-", "*", "+")):
            continue
        ref = parse_citation(s)
        if not (ref["doi"] or ref["year"]):
            continue
        refs.append(ref)
        if args.limit and len(refs) >= args.limit:
            break

    print(f"识别到 {len(refs)} 条疑似引用，逐条查询 Crossref（可能较慢）...")
    results = []
    for i, ref in enumerate(refs, 1):
        results.append(verify_one(ref))
        print(f"  [{i}/{len(refs)}] {ref['line'][:50]} -> {results[-1]['mark']}")
        time.sleep(0.2)

    out_lines = [
        "## 参考文献核查候选表（半自动 · 供人工复核）",
        "",
        "> 说明：本表由 verify_references.py 调用 Crossref（含 DOI 解析）自动生成，标记为“倾向”结论，",
        "> 最终 ✅/⚠️/❌ 以人工复核为准（必要时再用 PubMed / 期刊官网确认）。",
        "",
        "| 原引用 | 建议标记 | 匹配分 | 最佳匹配 | 依据 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in results:
        safe = r["ref"].replace("|", "\\|")
        matched = r["matched"].replace("|", "\\|")
        out_lines.append(f"| {safe} | {r['mark']} | {r['score']} | {matched} | {r['via']} |")
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out_lines) + "\n", encoding="utf-8-sig")
    print(f"已生成核查候选表: {output}")


if __name__ == "__main__":
    main()
