#!/usr/bin/env python3
"""Semi-automated reference verification against Crossref + PubMed (EN) with
Chinese-literature routing hints (CNKI / Wanfang / VIP / journal sites).

Reads a Markdown file containing citation lines (e.g. the appendix generated by
extract_references.py) and, for each line, resolves the DOI or queries
Crossref and PubMed (NCBI E-utilities) for English literature, while routing
Chinese-only citations to manual verification via Chinese databases. It
outputs a candidate check table (references.check.md) with a suggested mark,
so the organizer only needs to review the evidence instead of searching every
reference by hand.

Usage:
  python verify_references.py <references.md> [-o references.check.md]
"""

import argparse
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) DeepSeekSkill/1.0 (mailto:example@example.com)"
PUBMED_ESEARCH = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
PUBMED_ESUMMARY = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
DOI_RE = re.compile(r"10\.\d{4,9}/[^\s,;)\]（）】，。]+")
YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
SURNAME_RE = re.compile(r"(?<![\w-])([A-Z][A-Za-z\u00C0-\u024F\-]{2,})\s+(?:et al\.?|&|,|\(19|\(20|\.|$)")
STOP = {"the", "and", "of", "in", "on", "for", "with", "from", "to", "a", "an", "via", "by", "at", "its", "their", "his", "her"}
CJK_RE = re.compile(r"[\u4e00-\u9fff]")


def fetch_json(url, timeout=25):
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def tokens(text):
    return {w for w in re.findall(r"[A-Za-z][A-Za-z0-9'\-]{2,}", text.lower()) if w not in STOP}


def jaccard(a, b):
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def parse_citation(line):
    line = re.sub(r"^[-*+]\s*", "", line).strip()
    line = re.sub(r"^[✅⚠️❌]\s*", "", line)
    line = re.sub(r"（来源对话：.*$", "", line).strip()
    query = re.split(r"\s*—\s*|；实为|，实为", line)[0].strip()
    line = re.sub(r"^https?://doi\.org/", "", line).strip()
    doi = None
    m = DOI_RE.search(line)
    if m:
        doi = m.group(0).rstrip(".")
    year = None
    m = YEAR_RE.search(line)
    if m:
        year = int(m.group(0))
    surname = None
    m = SURNAME_RE.search(line)
    if m:
        surname = m.group(1)
    return {"line": line, "query": query, "doi": doi, "year": year, "surname": surname}


def title_of(item):
    t = item.get("title") or []
    return t[0] if t else ""


def authors_of(item):
    out = []
    for a in item.get("author", []):
        fam = a.get("family")
        if fam:
            out.append(fam)
    return out


def year_of(item):
    issued = item.get("issued") or {}
    parts = issued.get("date-parts") or [[None]]
    return parts[0][0]


def score_candidate(ref, item):
    score = 0.0
    cand_authors = authors_of(item)
    cand_year = year_of(item)
    cand_title = title_of(item)
    if ref["surname"] and any(a.lower() == ref["surname"].lower() for a in cand_authors):
        score += 0.4
    if ref["year"] and cand_year and abs(int(cand_year) - ref["year"]) <= 1:
        score += 0.3
    qt = tokens(re.sub(r"\(.*?\)", " ", ref["line"]))
    score += 0.3 * jaccard(qt, tokens(cand_title))
    return round(min(score, 1.0), 2), cand_title, cand_authors, cand_year


def suggest_mark(score, found):
    if not found:
        return "❌(倾向)"
    if score >= 0.75:
        return "✅(倾向)"
    if score >= 0.45:
        return "⚠️(倾向)"
    return "❌(倾向)"


def verify_one(ref):
    if CJK_RE.search(ref["line"]) and not ref["doi"] and not ref["surname"]:
        return _chinese_routing(ref)
    if ref["doi"]:
        try:
            data = fetch_json(f"https://api.crossref.org/works/{urllib.parse.quote(ref['doi'])}")
            item = data["message"]
            if not (ref["surname"] or ref["year"]):
                result = {
                    "ref": ref["line"],
                    "mark": "⚠️(需比对)",
                    "score": "-",
                    "matched": f"{title_of(item)} | {', '.join(authors_of(item)[:3])} | {year_of(item)}",
                    "via": f"DOI {ref['doi']}（可解析，匹配与否需人工比对）",
                }
                return _best_candidate(ref, result)
            score, title, authors, year = score_candidate(ref, item)
            result = {
                "ref": ref["line"],
                "mark": suggest_mark(score, True),
                "score": score,
                "matched": f"{title} | {', '.join(authors[:3])} | {year}",
                "via": f"DOI {ref['doi']}",
            }
            return _best_candidate(ref, result)
        except Exception as exc:  # noqa: BLE001
            # DOI 未命中时回退到书目检索，看论文是否以其他 DOI 存在
            fallback = _bibliographic(ref)
            fallback["ref"] = ref["line"]
            fallback["via"] = f"DOI {ref['doi']} 未命中（{exc}），回退标题检索"
            return _best_candidate(ref, fallback)

    return _best_candidate(ref, _bibliographic(ref, ref["query"]))


def _bibliographic(ref, query=None):
    query = query or ref["query"] or ref["line"][:160].replace("\n", " ")
    try:
        url = "https://api.crossref.org/works?rows=4&query.bibliographic=" + urllib.parse.quote(query)
        data = fetch_json(url)
        items = data.get("message", {}).get("items", [])
    except Exception as exc:  # noqa: BLE001
        return {"ref": ref["line"], "mark": "⚠️(网络失败)", "score": 0, "matched": str(exc), "via": "Crossref"}
    if not items:
        return {"ref": ref["line"], "mark": "❌(倾向)", "score": 0, "matched": "Crossref 无结果", "via": "Crossref"}
    best = None
    for item in items:
        s, t, a, y = score_candidate(ref, item)
        if best is None or s > best[0]:
            best = (s, t, a, y)
    s, t, a, y = best
    return {
        "ref": ref["line"],
        "mark": suggest_mark(s, True),
        "score": s,
        "matched": f"{t} | {', '.join(a[:3])} | {y}",
        "via": "Crossref 书目检索",
    }


def _pubmed_term(ref):
    """Build a PubMed query: species-like bigrams (e.g. Phalaenopsis aphrodite) + author + year."""
    parts = []
    line = re.sub(r"（来源对话：.*$", "", ref["line"])
    line = re.sub(r"\(.*?\)", " ", line)
    line = re.sub(r"\bet al\.?\b", " ", line, flags=re.I)
    skip2 = {"level", "assembly", "genetic", "physical", "mapping", "genome",
             "sequence", "analysis", "insights", "provides", "species",
             "evolution", "resources", "breeding", "research", "study",
             "plant", "plants", "flower", "floral", "development", "adaptive",
             "conservation", "chromosome"}
    species = []
    for a, b in re.findall(r"\b([A-Z][a-z]{2,})\s+([a-z]{2,})\b", line):
        if b.lower() in skip2:
            continue
        if ref["surname"] and a.lower() == ref["surname"].lower():
            continue
        species.append(f"{a} {b}")
    # 作者候选：取 "et al." 前的首/末词并用 OR（兼容中文拼音姓前名后与西方名前姓后）
    name_part = re.sub(r"（来源对话：.*$", "", ref["line"])
    m = re.search(r"\bet al\.?\b", name_part, flags=re.I)
    if m:
        words = re.findall(r"[A-Za-z][A-Za-z'\-]*", name_part[:m.start()])
        cand = []
        if words:
            cand.append(words[0])
            if len(words) > 1:
                cand.append(words[-1])
        cand = list(dict.fromkeys(c for c in cand if len(c) > 1))
        if cand:
            parts.append("(" + " OR ".join(f"{c}[Author]" for c in cand) + ")")
    if species:
        parts.append(" AND ".join(f'"{s}"' for s in species[:2]))
    else:
        words = [w for w in re.findall(r"[A-Za-z][A-Za-z0-9'\-]{2,}", line)
                 if w.lower() not in STOP and len(w) > 2]
        if ref["surname"]:
            words = [w for w in words if w.lower() != ref["surname"].lower()]
        if words:
            parts.append(" ".join(words[:4]))
    if ref["year"]:
        parts.append(f"{ref['year']}[PDAT]")
    return " AND ".join(parts)


def _pubmed_esearch(term, retmax=3):
    url = f"{PUBMED_ESEARCH}?db=pubmed&retmode=json&retmax={retmax}&term=" + urllib.parse.quote(term)
    data = fetch_json(url)
    return data.get("esearchresult", {}).get("idlist", [])


def _pubmed_esummary(pmids):
    url = f"{PUBMED_ESUMMARY}?db=pubmed&retmode=json&id=" + ",".join(pmids)
    data = fetch_json(url)
    result = data.get("result", {})
    items = []
    for uid in pmids:
        it = result.get(uid)
        if not it or it.get("error"):
            continue
        authors = []
        for a in it.get("authors", []) or []:
            name = (a.get("name") or "").strip()
            if name:
                authors.append(name.split()[0])
        year = None
        m = re.search(r"\b(19|20)\d{2}\b", it.get("pubdate", ""))
        if m:
            year = int(m.group(0))
        doi = None
        for aid in it.get("articleids", []) or []:
            if aid.get("idtype") == "doi":
                doi = aid.get("value")
                break
        items.append({
            "title": it.get("title", ""),
            "authors": authors,
            "journal": it.get("fulljournalname", "") or it.get("source", ""),
            "year": year,
            "volume": it.get("volume", ""),
            "pages": it.get("pages", ""),
            "doi": doi,
            "pmid": uid,
        })
    return items


def _pubmed_verify(ref):
    """Query PubMed (English literature) and return the best candidate (None if unreachable / no hit)."""
    term = _pubmed_term(ref)
    if not term:
        return None
    try:
        pmids = _pubmed_esearch(term)
        if not pmids and ref["year"]:
            # 年份限定过严时去掉年份重试
            relaxed = dict(ref)
            relaxed["year"] = None
            pmids = _pubmed_esearch(_pubmed_term(relaxed))
        if not pmids:
            return None
        items = _pubmed_esummary(pmids[:3])
    except Exception:  # noqa: BLE001
        return None
    if not items:
        return None
    best = None
    for item in items:
        fake = {
            "line": ref["line"],
            "query": ref["query"],
            "doi": item.get("doi"),
            "year": item.get("year"),
            "surname": ref["surname"],
        }
        s, t, a, y = score_candidate(fake, {
            "title": [item["title"]],
            "author": [{"family": x} for x in item["authors"]],
            "issued": {"date-parts": [[item["year"]]]},
        })
        if best is None or s > best[0]:
            best = (s, item)
    if best is None:
        return None
    s, item = best
    detail = f"{item['title']} | {', '.join(item['authors'][:3])} | {item['year']} | PMID:{item['pmid']}"
    overlap = len(tokens(ref["line"]) & tokens(item["title"]))
    if overlap < 2:
        # 标题几乎没有词重叠：即使作者/年份碰巧命中，也只给“倾向不确定”标记
        s = min(s, 0.44)
    return {
        "score": round(min(s + 0.05, 1.0), 2),  # slight bonus for PMID-anchored hit
        "matched": detail,
        "via": f"PubMed（PMID {item['pmid']}）",
    }


def _best_candidate(ref, crossref_result):
    """Merge Crossref and PubMed results, prefer the higher score."""
    if crossref_result.get("score") == "-":
        # DOI 已权威解析、仅需人工比对时，不再用 PubMed 低分结果覆盖
        return crossref_result
    pub = _pubmed_verify(ref)
    cross_score = crossref_result.get("score")
    if isinstance(cross_score, str) or cross_score is None:
        cross_score = 0.0
    pub_score = pub["score"] if pub else 0.0
    if pub and pub_score >= cross_score:
        return {
            "ref": ref["line"],
            "mark": suggest_mark(pub["score"], True),
            "score": pub["score"],
            "matched": pub["matched"],
            "via": pub["via"],
        }
    return crossref_result


def _chinese_routing(ref):
    """Chinese-only citations: no PubMed/Crossref auto-check; route to CNKI/Wanfang/VIP."""
    return {
        "ref": ref["line"],
        "mark": "⚠️(中文文献·需人工)",
        "score": "-",
        "matched": "中文文献不在 PubMed/Crossref 覆盖范围，需人工经知网 CNKI、万方、维普、期刊官网核对题录",
        "via": "中文文献路径（CNKI / 万方 / 维普 / 期刊官网）",
    }


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:  # noqa: BLE001
        pass
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("input", help="包含参考文献行的 Markdown 文件（如 extract_references.py 生成的 references.md）")
    parser.add_argument("-o", "--output", default="references.check.md", help="输出核查候选表（默认 references.check.md）")
    parser.add_argument("--limit", type=int, default=0, help="可选：最多核查前 N 条（0=全部）")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        sys.exit(f"输入文件不存在: {input_path}")
    lines = input_path.read_text(encoding="utf-8-sig").splitlines()
    refs = []
    for ln in lines:
        s = ln.strip()
        if not s.startswith(("-", "*", "+")):
            continue
        ref = parse_citation(s)
        if not (ref["doi"] or ref["year"]):
            continue
        refs.append(ref)
        if args.limit and len(refs) >= args.limit:
            break

    print(f"识别到 {len(refs)} 条疑似引用，逐条查询 Crossref + PubMed（英文，可能较慢），中文文献走人工核对提示...")
    results = []
    for i, ref in enumerate(refs, 1):
        results.append(verify_one(ref))
        print(f"  [{i}/{len(refs)}] {ref['line'][:50]} -> {results[-1]['mark']}")
        time.sleep(0.2)

    out_lines = [
        "## 参考文献核查候选表（半自动 · 供人工复核）",
        "",
        "> 说明：本表由 verify_references.py 自动生成。英文文献经 Crossref（含 DOI 解析）与",
        "> PubMed（NCBI E-utilities）两个英文文献数据库核查；中文文献不在两库覆盖范围，",
        "> 已给出人工核对路径（知网 CNKI、万方、维普、期刊官网）。所有标记均为“倾向”结论，",
        "> 最终 ✅/⚠️/❌ 以人工复核为准（必要时再用 Web of Science / 期刊官网确认）。",
        "",
        "| 原引用 | 建议标记 | 匹配分 | 最佳匹配 | 依据 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in results:
        safe = r["ref"].replace("|", "\\|")
        matched = r["matched"].replace("|", "\\|")
        out_lines.append(f"| {safe} | {r['mark']} | {r['score']} | {matched} | {r['via']} |")
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out_lines) + "\n", encoding="utf-8-sig")
    print(f"已生成核查候选表: {output}")


if __name__ == "__main__":
    main()
